### ISSUE TITLE
Make GitHub Auth Work in Development

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#360]
login via github does not work locally, github shows 404

**Comment by denisemauldin** [comment]
What I'm seeing is that when I click the `Sign Up/Sign In` link it redirects in the current window instead of opening a new popup/new tab, this means that the `AuthPopupPage` never goes away when `postMessageToOpener` succeeds.  If I go back to `http://localhost:3000` from the `http://localhost:3000/authenticated?code=aa62af9d085e48b1d4bd` page, then I am logged in.

**Comment by stushurik** [comment]
@curran @denisemauldin seems works now if proper env vars are set

**Comment by curran** [comment]
Nice. I'm curious @denisemauldin after getting the environment variables squared away, do you still see the buggy behavior you described earlier? I'm not able to reproduce it locally. Thanks!

**Comment by curran** [comment]
This has been addressed, closing.
