### ISSUE TITLE
Show "Forks of X" in top of forks page

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#366]
We have now a "forks" page that shows forks of a particular viz. For example:

https://vizhub.com/curran/6ec4f3dd10ac4fcdb5f759d38e7ceefa/forks

That page is also in need of a header at the top saying something like "Forks of X" where X is the name of the viz.

No designs exist for this.

The first pass can be text only, but the thumbnail is available so maybe that could be featured somehow as well (maybe in a second pass).

**Comment by denisemauldin** [comment]
I updated to use an interactor for Forks data.  I added the current visualization information to the page since I had it and there were no designs and it seemed to be the best way to distinguish the current visualization thumbnail from the Fork thumbnails, but please let me know what updates should be made.

![Screen Shot 2020-07-11 at 6 23 14 PM](https://user-images.githubusercontent.com/196261/87236914-f4100e80-c3a3-11ea-978c-1fdffc9f4328.png)
