### ISSUE TITLE
(Styling) Profile page:Avatar some spacing on left

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#369]
Avatar is too close to the left, wonder some spacing is required?
![avatarLeft](https://user-images.githubusercontent.com/13540669/86191300-b47c3380-bb14-11ea-9810-7315102bfe39.png)

**Comment by curran** [comment]
Indeed, the styles need a bit of finesse.

@denisemauldin This might be a good one for you to look at, as a second pass of the new additions.

Ideas for directions:
 * Add margin/padding to the container for the user avatar such that it matches the padding of the VizHub logo (maybe 5px or so?).
 * For the viz previews grid, make it fill up the horizontal space, so that the edges align with the rest of the design. This appears doable using [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) `justify-content: space-between`.
