### ISSUE TITLE
Fork count wrong

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#385]
Go to 
1. most forked
2. down, there is my preview with 11 forks.
3. click on fork shows less than 11 forks.

**Comment by curran** [comment]
@stushurik I have a theory about this: it could be because I backfilled the values outside of ShareDB, while the ShareDB system was still running. I believe ShareDB maintains a cache of sorts for the document state, so when we set values directly with Mongo, ShareDB's cache could overwrite the values (as it doesn't know they changed).

I think the best solution to this would be to backfill the values via ShareDB. This is tracked as **NPM Script for Backfilling Forks Count with ShareDB** #384

**Comment by curran** [comment]
Closing in favor of #384
